### ISSUE TITLE
Set right fonts to labels and buttons

### ISSUE THREAD

**Issue by haroldolivieri** [haroldolivieri/CrowdedInfo#4]
<img width="652" alt="screen shot 2016-11-03 at 10 40 15 am" src="https://cloud.githubusercontent.com/assets/6575718/19966211/fa952230-a1b1-11e6-9029-f09905ce5656.png">

**Comment by haroldolivieri** [comment]
same in mobile

**Comment by FabioGois** [comment]
Inside the section _**"Sobre o projeto"**_ what font will be used?
